# Generated by Django 4.2.2 on 2023-06-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hscode', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hscode',
            options={'verbose_name': 'HScode'},
        ),
    ]
